export const JWT_GUARD_METADATA_KEY = 'JWT_GUARD_METADATA_KEY';
export const API_VERSION_GUARD_METADATA_KEY = 'API_VERSION_GUARD_METADATA_KEY';
export const ADMIN_PERMISSION_GUARD_METADATA_KEY = Symbol('ADMIN_PERMISSION_GUARD_METADATA_KEY');
